apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: testgo0227actions
  janus-idp.io/tekton: testgo0227actions
  backstage.io/kubernetes-id: testgo0227actions
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: testgo0227actions
resources:
- deployment.yaml
- route.yaml
- service.yaml
